# Generated by Django 3.2.13 on 2022-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainfall',
            name='raingauge_code',
            field=models.IntegerField(),
        ),
    ]
