# Generated by Django 3.2.13 on 2022-06-30 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainfall',
            name='gubn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rainfall', to='data.guname'),
        ),
        migrations.AlterField(
            model_name='sewerpipe',
            name='gubn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sewer_pipe', to='data.guname'),
        ),
    ]
