# Generated by Django 3.2.13 on 2022-06-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_rainfall_raingauge_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainfall',
            name='raingauge_code',
            field=models.CharField(max_length=5),
        ),
    ]
